version: '3.7'

services:

  davdsm_app:
    container_name: davdsm_app
    build:
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - './app:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
