version: "3.7"

services:
  davdsm_app:
    container_name: davdsm_app
    build:
      context: .
      dockerfile: ./app/Dockerfile
    restart: unless-stopped
    volumes:
      - "./app:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  davdsm_api:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: davdsm_api
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - /api:/api
